# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:              Alex McFarlane
subtitle:           Useful Stuff
description:        
keywords:           physics monte-carlo mathematics hamiltonian-monte-carlo hmc
                    quantitative-finance deep learning neural networks cloud python
                    learning blog
language:           "en" # default language of the blog. Language codes:
                         # www.w3schools.com/tags/ref_language_codes.asp
baseurl:            ""   # the subpath of your site, e.g. /blog
# the base hostname & protocol for your site. Look at robots.txt as well!
url:                "http://flipdazed.github.io"
permalink:          /blog/:categories/:title
cover:              /assets/math2.jpg
disqus_shortname:   flipdazed
google_tracking_id: UA-84554204-1
google_ad_client:   ca-pub-6286561277379272

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
  math_engine: mathjax
include: ['_pages']
exclude: [vendor]
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag
